<?php

namespace MemberBundle\Repository;

use MemberBundle\Entity\Member;

/**
 * MemberSubscriptionHistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberSubscriptionHistoricalRepository extends \Doctrine\ORM\EntityRepository
{
}
