member_member_group:
    resource: "@MemberBundle/Controller/MemberGroupController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
member:
    resource: "@MemberBundle/Controller/"
    type:     annotation
subscription:
    resource: "@SubscriptionBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
accounting:
    resource: "@AccountingBundle/Controller/"
    type:     annotation
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
