# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # Security
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router', '@security.password_encoder']
    # Service helper
    app.email_templating:
        class: AppBundle\Service\MailerTemplating
        arguments: ['@mailer', '@templating']
    # Form Handler
    app.form.handler.security_forgot_password:
        class: AppBundle\Form\Handler\ForgotPasswordFormHandler
        arguments: ['@form.factory', '@translator.default', '@app.email_templating', '%senderMail%']
    app.form.handler.security_change_password:
        class: AppBundle\Form\Handler\ChangePasswordHandler
        arguments: ['@form.factory']
    app.form.handler.setting_app:
        class: AppBundle\Form\Handler\SettingAppHandler
        arguments: ['@form.factory']
    # Repository
    app.repository.setting:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Setting
    # Manager
    app.manager.security:
        class: AppBundle\Manager\SecurityManager
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder', '@translator.default' , '@app.email_templating', 'security/askPasswordEmail.html.twig', '%sendermail%']
    app.manager.setting:
        class: AppBundle\Manager\SettingManager
        arguments: ['@app.repository.setting']