# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # Security
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router', '@security.password_encoder']
    # Service helper
    app.email_templating:
        class: AppBundle\Service\MailerTemplating
        arguments: ['@mailer', '@templating']
    # Form Handler
    app.form.handler.security_forgot_password:
        class: AppBundle\Form\Handler\ForgotPasswordFormHandler
        arguments: ['@form.factory', '@translator.default', '@app.email_templating', '%senderMail%']
    app.manager.security_ask_password:
        class: AppBundle\Manager\SecurityAskPasswordManager
        arguments: ['@doctrine.orm.entity_manager', '@translator.default' , '@app.email_templating', 'security/askPasswordEmail.html.twig', '%sendermail%']