# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # Repository
    app.repository.setting:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Setting
    # Security
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router', '@security.password_encoder']
    # Service helper
    app.email_templating:
        class: AppBundle\Service\MailerTemplating
        arguments: ['@mailer', '@templating']
    # Form Model
    app.form.model.app_setting:
        class: AppBundle\Form\Model\SettingAppModel
    # Form Handler
    app.form.handler.security_forgot_password:
        class: AppBundle\Form\Handler\ForgotPasswordFormHandler
        arguments: ['@form.factory', '@translator.default', '@app.email_templating', '%senderMail%']
    app.form.handler.security_change_password:
        class: AppBundle\Form\Handler\ChangePasswordHandler
        arguments: ['@form.factory']
    app.form.handler.setting_app:
        class: AppBundle\Form\Handler\SettingAppHandler
        arguments: ['@form.factory', '@app.form.model.app_setting', '@app.manager.setting', '%kernel.root_dir%']
    app.subscription.form.handler.periodicity:
        class: AppBundle\Form\Handler\PeriodicityFormHandler
        arguments: ['@form.factory']
    # Twig extension
    app.twig_extension.setting:
        class: AppBundle\Twig\SettingExtension
        arguments: ['@app.repository.setting']
        tags:
            - {name: twig.extension}
    # Manager
    app.manager.security:
        class: AppBundle\Manager\SecurityManager
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder', '@translator.default' , '@app.email_templating', 'security/askPasswordEmail.html.twig', '%sendermail%']
    app.manager.setting:
        class: AppBundle\Manager\SettingManager
        arguments: ['@app.repository.setting']
    app.subscription.manager.periodicity:
        class: AppBundle\Manager\PeriodicityManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    # Handler
    app.handler.page_historical:
        class: AppBundle\Handler\PageHistoricalHandler
        arguments: ['@session', 'page_historical']