<?php

namespace EmailBundle\Repository;

/**
 *
 * EmailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailingRepository extends EmailRepository
{
}
