<?php

namespace EmailBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 *
 * EmailHistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailHistoricalRepository extends EntityRepository
{
}
