parameters:
    # CREDENTIALS
    credentialVoterEmailSystemEmail:
        app.security.credential.view: EMAIL_SYSTEM_EMAIL_VIEW
        app.security.credential.edit: EMAIL_SYSTEM_EMAIL_EDIT
    credentialVoterEmailEmailing:
        app.security.credential.view: EMAIL_EMAILING_VIEW
        app.security.credential.create: EMAIL_EMAILING_CREATE
        app.security.credential.edit: EMAIL_EMAILING_EDIT
        app.security.credential.delete: EMAIL_EMAILING_DELETE
    credentialVoterEmailSetting:
        member.security.credential.setting: EMAIL_SETTING_EDIT
    masterCredentialMenuEmailEmailing: EMAIL_EMAILING_MANAGER_MENU
    credentialVoterEmailMenu:
        EMAIL_EMAILING_VIEW: EMAIL_EMAILING_VIEW
    masterCredentialMenuEmailSystemEmail: EMAIL_SYSTEM_EMAIL_MANAGER_MENU
    credentialVoterEmailSystemEmailMenu:
        EMAIL_SYSTEM_EMAIL_VIEW: EMAIL_SYSTEM_EMAIL_VIEW