parameters:
    credentialVoterUserGroup:
        app.security.credential.view: USER_GROUP_VIEW
        app.security.credential.create: USER_GROUP_CREATE
        app.security.credential.edit: USER_GROUP_EDIT
        app.security.credential.delete: USER_GROUP_DELETE
