parameters:
    credentialVoterUserUser:
        app.security.credential.view: USER_USER_VIEW
        app.security.credential.create: USER_USER_CREATE
        app.security.credential.edit: USER_USER_EDIT
        app.security.credential.delete: USER_USER_DELETE
    credentialVoterUserGroup:
        app.security.credential.view: USER_GROUP_VIEW
        app.security.credential.create: USER_GROUP_CREATE
        app.security.credential.edit: USER_GROUP_EDIT
        app.security.credential.delete: USER_GROUP_DELETE
    masterCredentialMenuUser: USER_MANAGER_MENU
    credentialVoterUserMenu:
        USER_USER_VIEW: USER_USER_VIEW
        USER_GROUP_VIEW: USER_GROUP_VIEW