services:
    # EVENT LISTENER
    user_group_credential_event:
        class: UserBundle\EventListener\UserGroupCredentialEventListener
        arguments: ['%credentialVoterUserGroup%', 'user.group.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    user_usercredential_event:
        class: UserBundle\EventListener\UserCredentialEventListener
        arguments: ['%credentialVoterUserUser%', 'user.user.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    user.menu_setting_credential.event:
        class: AppBundle\EventListener\AppMenuCredentialEventListener
        arguments: ['%credentialvoterusermenu%']
        tags:
            - { name: kernel.event_listener, event: app.security.menu.credential.event, method: onProvideCredential }
    user.user.profile_route.event:
        class: AppBundle\EventListener\AppUserProfileRouteEventListener
        arguments: ['user', 'user_profile']
        tags:
            - { name: kernel.event_listener, event: app.user.profile_route.event, method: onProvideProfileRoute }
    # VOTER
    user_group_voter:
        class: UserBundle\Security\UserGroupVoter
        autowire: true
        arguments: ['%credentialVoterUserGroup%']
        tags:
            - {name: security.voter}
    user_user_voter:
        class: UserBundle\Security\UserVoter
        autowire: true
        arguments: ['%credentialVoterUserUser%']
        tags:
            - {name: security.voter}
    user_menu_voter:
        class: UserBundle\Security\UserMenuVoter
        autowire: true
        arguments: ['%credentialvoterusermenu%', '%masterCredentialMenuUser%']
        tags:
            - {name: security.voter}
    # Form Handler
    user.form.handler.group:
        class: UserBundle\Form\Handler\UserGroupFormHandler
        arguments: ['@form.factory', '@service_container']
    user.form.handler.user:
        class: UserBundle\Form\Handler\UserFormHandler
        arguments: ['@form.factory', '@service_container']
    user.form.handler.user_list_filter:
        class: UserBundle\Form\Handler\UserListFilterHandler
        arguments: ['@form.factory', '@service_container']
    # Manager
    user.manager.group:
        class: UserBundle\Manager\UserGroupManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    user.manager.user:
        class: UserBundle\Manager\UserManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']