parameters:
    credentialVoterAppSetting:
        app.security.credential.view: APP_SETTING_VIEW
    masterCredentialVoterAppSettingMenu: APP_MASTER_SETTING_MENU
    credentialVoterAppSettingMenu:
        APP_SETTING_VIEW: APP_SETTING_VIEW