services:
    # EVENT LISTENER
    app.setting.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterAppSetting%', 'app.setting.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    app.menu_setting_credential.event:
        class: AppBundle\EventListener\AppMenuCredentialEventListener
        arguments: ['%credentialvoterAppsettingmenu%']
        tags:
            - { name: kernel.event_listener, event: app.security.menu.credential.event, method: onProvideCredential }
    # VOTER
    app.setting.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterAppSetting%']
        tags:
            - {name: security.voter}
    app.master_setting.voter:
        class: AppBundle\Security\AppMenuSettingVoter
        autowire: true
        arguments: ['@service_container', '%masterCredentialVoterAppSettingMenu%']
        tags:
            - {name: security.voter}