parameters:
    # CREDENTIALS
    credentialVoterMemberMembers:
        app.security.credential.view: MEMBER_MEMBER_VIEW
        app.security.credential.create: MEMBER_MEMBER_CREATE
        app.security.credential.edit: MEMBER_MEMBER_EDIT
#        app.security.credential.delete: MEMBER_MEMBER_DELETE
    credentialVoterMemberGroups:
        app.security.credential.view: MEMBER_GROUPS_VIEW
        app.security.credential.create: MEMBER_GROUPS_CREATE
        app.security.credential.edit: MEMBER_GROUPS_EDIT
        app.security.credential.delete: MEMBER_GROUPS_DELETE
    credentialVoterMemberStatus:
        app.security.credential.view: MEMBER_STATUS_VIEW
        app.security.credential.create: MEMBER_STATUS_CREATE
        app.security.credential.edit: MEMBER_STATUS_EDIT
        app.security.credential.delete: MEMBER_STATUS_DELETE
    credentialVoterMemberSubscription:
        app.security.credential.view: MEMBER_SUBSCRIPTION_VIEW
        member.subscription.credential.create: MEMBER_SUBSCRIPTION_CREATE
        member.subscriptionFee.credential.save: MEMBER_SUBSCRIPTION_FEE_SAVE
    credentialVoterMemberSetting:
        member.security.credential.setting: MEMBER_SETTING_EDIT
    masterCredentialMenuMember: MEMBER_MANAGER_MENU
    credentialVoterMemberMenu:
        MEMBER_MEMBER_VIEW: MEMBER_MEMBER_VIEW
        MEMBER_STATUS_VIEW: MEMBER_STATUS_VIEW