parameters:
    credentialVoterMemberMembers:
        MEMBER_STATUS_VIEW: 'app.security.credential.view'
        MEMBER_STATUS_CREATE: 'app.security.credential.create'
        MEMBER_MEMBER_EDIT: 'app.security.credential.edit'
        MEMBER_MEMBER_DELETE: 'app.security.credential.delete'
    credentialVoterMemberStatus:
        MEMBER_STATUS_VIEW: 'app.security.credential.view'
        MEMBER_STATUS_CREATE: 'app.security.credential.create'
        MEMBER_STATUS_EDIT: 'app.security.credential.edit'
        MEMBER_STATUS_DELETE: 'app.security.credential.delete'