parameters:
    credentialVoterMemberMembers:
        app.security.credential.view: MEMBER_STATUS_VIEW
        app.security.credential.create: MEMBER_STATUS_CREATE
        app.security.credential.edit: MEMBER_MEMBER_EDIT
        app.security.credential.delete: MEMBER_MEMBER_DELETE
    credentialVoterMemberStatus:
        app.security.credential.view: MEMBER_STATUS_VIEW
        app.security.credential.create: MEMBER_STATUS_CREATE
        app.security.credential.edit: MEMBER_STATUS_EDIT
        app.security.credential.delete: MEMBER_STATUS_DELETE