services:
    # EVENT LISTENER
    member.status.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterMemberStatus%', 'member.status.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.member.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterMemberMembers%', 'member.member.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.subscription.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialvotermembersubscription%', 'member.subscription.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    # VOTER
    member.member.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterMemberMembers%']
        tags:
            - {name: security.voter}
    member.status.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterMemberStatus%']
        tags:
            - {name: security.voter}
    member.subscription.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialvotermembersubscription%']
        tags:
            - {name: security.voter}
    member.menu.voter:
        class: MemberBundle\security\MemberMenuVoter
        autowire: true
        arguments: ['%credentialVoterMemberMenu%', '%masterCredentialMenuMember%']
        tags:
            - {name: security.voter}
    # MANAGER
    member.manager.member:
        class: MemberBundle\Manager\MemberMemberManager
        #, subscriptionDateEnd: 'subscriptions.endDate'
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.status:
        class: MemberBundle\Manager\MemberStatusManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.subscription_historical:
        class: MemberBundle\Manager\MemberSubscriptionHistoricalManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.subscription_fee:
        class: MemberBundle\Manager\MemberSubscriptionFeeManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    # FORM
    member.form.handler.member:
        class: MemberBundle\Form\Handler\MemberFormHandler
        arguments: ['@form.factory', '@service_container']
    member.form.handler.subscription_historical:
        class: MemberBundle\Form\Handler\MemberSubscriptionHistoricalFormHandler
        arguments: ['@form.factory', '@service_container']
    member.form.handler.subscription_fee:
        class: MemberBundle\Form\Handler\MemberSubscriptionFeeFormHandler
        arguments: ['@form.factory', '@service_container']
    # CONTROLLER
    member.controller.status:
        class: MemberBundle\Controller\MemberStatusController
        arguments: ['@service_container']