#services:
#    member_member_voter:
#        class: MemberBundle\Security\MemberVoter
#        autowire: true
#        tags:
#            - {name: security.voter}
#    member_status_voter:
#        class: MemberBundle\Security\MemberStatusVoter
#        autowire: true
#        tags:
#            - {name: security.voter}