services:
    # EVENT LISTENER
    member_status_credential_event:
        class: MemberBundle\EventListener\StatusCredentialEventListener
        arguments: ['%credentialVoterMemberStatus%', 'member.status.credential']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    # VOTER
    member_member_voter:
        class: MemberBundle\Security\MemberVoter
        autowire: true
        tags:
            - {name: security.voter}
    member_status_voter:
        class: MemberBundle\Security\MemberStatusVoter
        autowire: true
        arguments: ['%credentialVoterMemberStatus%']
        tags:
            - {name: security.voter}