services:
    # EVENT LISTENER
    member.status.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterMemberStatus%', 'member.status.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.member.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterMemberMembers%', 'member.member.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.subscription.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialvotermembersubscription%', 'member.subscription.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.setting.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterMemberSetting%', 'member.setting.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    member.dashboard.bundle.event:
        class: AppBundle\EventListener\AppDashboardBundleEventListener
        arguments: ['member.dashboard.tableTitleTop10', '%member.dashboard.tableTitleTop10%']
        tags:
            - { name: kernel.event_listener, event: app.dashboard.bundle.event, method: onProvideBundle }
    # VOTER
    member.member.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterMemberMembers%']
        tags:
            - {name: security.voter}
    member.status.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterMemberStatus%']
        tags:
            - {name: security.voter}
    member.subscription.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialvotermembersubscription%']
        tags:
            - {name: security.voter}
    member.setting.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterMemberSetting%']
        tags:
            - {name: security.voter}
    member.menu.voter:
        class: MemberBundle\security\MemberMenuVoter
        autowire: true
        arguments: ['%credentialVoterMemberMenu%', '%masterCredentialMenuMember%']
        tags:
            - {name: security.voter}
    # MANAGER
    member.manager.member:
        class: MemberBundle\Manager\MemberMemberManager
        #, subscriptionDateEnd: 'subscriptions.endDate'
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.status:
        class: MemberBundle\Manager\MemberStatusManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.subscription_historical:
        class: MemberBundle\Manager\MemberSubscriptionHistoricalManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    member.manager.subscription_fee:
        class: MemberBundle\Manager\MemberSubscriptionFeeManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator', '@session']
    # FORM MODEL
    member.form.model.member_setting:
        class: MemberBundle\Form\Model\MemberSettingModel
    # FORM HANDLER
    member.form.handler.member:
        class: MemberBundle\Form\Handler\MemberFormHandler
        arguments: ['@form.factory', '@service_container']
    member.form.handler.subscription_historical:
        class: MemberBundle\Form\Handler\MemberSubscriptionHistoricalFormHandler
        arguments: ['@form.factory', '@service_container']
    member.form.handler.subscription_fee:
        class: MemberBundle\Form\Handler\MemberSubscriptionFeeFormHandler
        arguments: ['@form.factory', '@service_container']
    member.form.handler.member_setting:
        class: MemberBundle\Form\Handler\MemberSettingHandler
        arguments: ['@form.factory', '@member.form.model.member_setting', '@app.manager.setting']
    # CONTROLLER
    member.controller.status:
        class: MemberBundle\Controller\MemberStatusController
        arguments: ['@service_container']
    member.controller.dashboard:
        class: MemberBundle\Controller\DashboardController
        arguments: ['@service_container']
    member.controller.setting:
        class: MemberBundle\Controller\MemberSettingController
        arguments: ['@service_container']
