parameters:
    credentialVoterSubscriptionSubscription:
        app.security.credential.view: SUBSCRIPTION_SUBSCRIPTION_VIEW
        app.security.credential.create: SUBSCRIPTION_SUBSCRIPTION_CREATE
        app.security.credential.edit: SUBSCRIPTION_SUBSCRIPTION_EDIT
        app.security.credential.delete: SUBSCRIPTION_SUBSCRIPTION_DELETE
    credentialVoterSubscriptionPeriodicity:
        app.security.credential.view: SUBSCRIPTION_PERIODICITY_VIEW
        app.security.credential.create: SUBSCRIPTION_PERIODICITY_CREATE
        app.security.credential.edit: SUBSCRIPTION_PERIODICITY_EDIT
        app.security.credential.delete: SUBSCRIPTION_PERIODICITY_DELETE
    credentialVoterSubscriptionPaymentType:
        app.security.credential.view: SUBSCRIPTION_PAYMENT_TYPE_VIEW
        app.security.credential.create: SUBSCRIPTION_PAYMENT_TYPE_CREATE
        app.security.credential.edit: SUBSCRIPTION_PAYMENT_TYPE_EDIT
        app.security.credential.delete: SUBSCRIPTION_PAYMENT_TYPE_DELETE
    masterCredentialMenuSubscription: SUBSCRIPTION_MANAGER_MENU
    credentialVoterMenuSubscription:
        SUBSCRIPTION_SUBSCRIPTION_VIEW: SUBSCRIPTION_SUBSCRIPTION_VIEW
        SUBSCRIPTION_PERIODICITY_VIEW: SUBSCRIPTION_PERIODICITY_VIEW
        SUBSCRIPTION_PAYMENT_TYPE_VIEW: SUBSCRIPTION_PAYMENT_TYPE_VIEW