services:
    # EVENT LISTENER
    subscription.configure_menu_listener:
        class: SubscriptionBundle\EventListener\ConfigureMenuListener
        arguments: ['@translator', '@security.authorization_checker']
        tags:
            - { name: kernel.event_listener, event: app.menu_configure, method: onMenuConfigure }
    subscription.subscription.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterSubscriptionSubscription%', 'subscription.subscription.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    subscription.paymentType.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterSubscriptionPaymentType%', 'subscription.paymentType.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    subscription.periodicity.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterSubscriptionPeriodicity%', 'subscription.periodicity.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    subscription.dashboard.bundle.event:
        class: AppBundle\EventListener\AppDashboardBundleEventListener
        arguments: ['subscription.dashboard.totalFeeAmountCard', '%subscription.dashboard.totalFeeAmountCard%']
        tags:
            - { name: kernel.event_listener, event: app.dashboard.bundle.event, method: onProvideBundle }
    # VOTER
    subscription.subscritpion.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterSubscriptionSubscription%']
        tags:
            - {name: security.voter}
    subscription.periodicity.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterSubscriptionPeriodicity%']
        tags:
            - {name: security.voter}
    subscription.paymentType.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterSubscriptionPaymentType%']
        tags:
            - {name: security.voter}
    subscription_menu_voter:
        class: SubscriptionBundle\Security\SubscriptionMenuVoter
        autowire: true
        arguments: ['%credentialVoterMenuSubscription%', '%masterCredentialMenuSubscription%']
        tags:
            - {name: security.voter}
    # Repository
    subscription.repository.subscription:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - SubscriptionBundle\Entity\Subscription

    # Form handler
    subscription.form.handler.periodicity:
        class: SubscriptionBundle\Form\Handler\PeriodicityFormHandler
        arguments: ['@form.factory']
    subscription.form.handler.subscription:
        class: SubscriptionBundle\Form\Handler\SubscriptionFormHandler
        arguments: ['@form.factory']
    subscription.form.handler.subscription_fee_list_filter:
        class: SubscriptionBundle\Form\Handler\SubscriptionFeeListFilterHandler
        arguments: ['@form.factory']
    # Twig extension
    subscription.twig_extension.subscription:
        class: SubscriptionBundle\Twig\SubscriptionExtension
        arguments: ['@subscription.repository.subscription']
        tags:
            - {name: twig.extension}

    # Manager
    subscription.manager.periodicity:
        class: SubscriptionBundle\Manager\PeriodicityManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    subscription.manager.subscription:
        class: SubscriptionBundle\Manager\SubscriptionManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    subscription.manager.paymentType:
        class: SubscriptionBundle\Manager\PaymentTypeManager
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']

    # Controller
    subscription.controller.dashboard:
        class: SubscriptionBundle\Controller\DashboardController
        arguments: ['@service_container']
    # Validator
    subscription.validator.subscription_exist:
        class: SubscriptionBundle\Validator\SubscriptionExistValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - {name: validator.constraint_validator, alias: subscription_fee.validator.import.subscription_exist}
    subscription.validator.payment_exist:
        class: SubscriptionBundle\Validator\PaymentTypeExistValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - {name: validator.constraint_validator, alias: subscription_fee.validator.import.payment_exist}
