<?php

namespace EmailSystemBundle\Repository;

use EmailBundle\Repository\EmailRepository;

/**
 *
 * EmailSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailSystemRepository extends EmailRepository
{
}
