parameters:
    # CREDENTIALS
    credentialVoterEmailSystemEmail:
        app.security.credential.view: EMAIL_SYSTEM_EMAIL_VIEW
        app.security.credential.edit: EMAIL_SYSTEM_EMAIL_EDIT
    masterCredentialMenuEmailSystemEmail: EMAIL_SYSTEM_EMAIL_MANAGER_MENU
    credentialVoterEmailSystemEmailMenu:
        EMAIL_SYSTEM_EMAIL_VIEW: EMAIL_SYSTEM_EMAIL_VIEW