services:
    # EVENT LISTENER
    email_system.email_system.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterEmailSystemEmail%', 'email.system_email.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    # VOTER
    email_system.email_system.voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterEmailSystemEmail%']
        tags:
            - {name: security.voter}
    email_system.email_system.menu.voter:
        class: AppBundle\Security\AppMenuVoter
        autowire: true
        arguments: ['%credentialVoterEmailSystemEmail%', '%masterCredentialMenuEmailSystemEmail%']
        tags:
            - {name: security.voter}
    # MANAGER
    # FORM MODEL
    # FORM HANDLER
    email_system.form.handler.email_system:
        class: EmailSystemBundle\Form\Handler\EmailSystemFormHandler
        arguments: ['@form.factory']
    # CONTROLLER
    # Validator