services:
    accounting.manager.accounting:
        class: AccountingBundle\Manager\AccountingManager
        autowire: true
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    accounting.manager.exercise:
        class: AccountingBundle\Manager\ExerciseManager
        autowire: true
        arguments: ['@doctrine.orm.entity_manager', '@knp_paginator']
    accounting.form.entry:
        class: AccountingBundle\Form\Handler\EntryFormHandler
        arguments: ['@form.factory', '@service_container']
    accounting.form.solde:
        class: AccountingBundle\Form\Handler\SoldeFormHandler
        arguments: ['@form.factory', '@accounting.manager.accounting']
    accounting.form.exercise:
        class: AccountingBundle\Form\Handler\ExerciseFormHandler
        arguments: ['@form.factory', '@accounting.manager.exercise']
    # EVENT LISTENER
    accounting.account.credential.event:
        class: AppBundle\EventListener\AppCredentialEventListener
        arguments: ['%credentialVoterAccounting%', 'accounting.security.credential.title']
        tags:
            - { name: kernel.event_listener, event: app.security.credential.event, method: onProvideCredential }
    # VOTER
    accounting_voter:
        class: AppBundle\Security\appVoter
        autowire: true
        arguments: ['%credentialVoterAccounting%']
        tags:
            - {name: security.voter}
    accounting_menu_voter:
        class: AppBundle\Security\AppVoter
        autowire: true
        arguments: ['%credentialVoterAccountingMenu%']
        tags:
            - {name: security.voter}
